Repository nhnacademy-be10-WannaB/wannab-user-service, pull requests merged in 2025-07, with the labels that each got.

#64 feat: 로그아웃, 회원탈퇴(State변경)
  .github/workflows/merge-after-pr.yml
  .github/workflows/test-on-pr.yml
  http/request.http
  pom.xml
  src/main/java/shop/wannab/userservice/global/config/DataSourceConfig.java
  src/main/java/shop/wannab/userservice/global/config/QuerydslConfig.java
  src/main/java/shop/wannab/userservice/user/controller/UserController.java
  src/main/java/shop/wannab/userservice/user/repository/Impl/UserQueryDslRepositoryImpl.java
  src/main/java/shop/wannab/userservice/user/repository/UserQueryDslRepository.java
  src/main/java/shop/wannab/userservice/user/repository/UserRepository.java
  src/main/java/shop/wannab/userservice/user/service/UserService.java
  src/main/java/shop/wannab/userservice/user/service/UserServiceImpl.java
  src/main/resources/application-ci.yml
  src/main/resources/logback-spring.xml
Labels: Feature

#71 <69/exception-address : 예외처리>
  src/main/java/shop/wannab/userservice/address/controller/UserAddressController.java
  src/main/java/shop/wannab/userservice/address/exception/AlreadyExistsUserAddressException.java
  src/main/java/shop/wannab/userservice/address/repository/UserAddressRepository.java
  src/main/java/shop/wannab/userservice/address/service/Impl/UserAddressServiceImpl.java
  src/main/java/shop/wannab/userservice/address/service/UserAddressService.java
  src/main/java/shop/wannab/userservice/global/advice/GlobalExceptionHandler.java
  src/main/java/shop/wannab/userservice/utils/ResponseCode.java
Labels: Refactor

#74 휴면해제 인증 : <16/user-unlock : 인증코드 발급, 검증>
  http/request.http
  src/main/java/shop/wannab/userservice/auth/DoorayMessageClient.java
  src/main/java/shop/wannab/userservice/auth/controller/AuthController.java
  src/main/java/shop/wannab/userservice/auth/controller/request/SendMessageRequest.java
  src/main/java/shop/wannab/userservice/auth/controller/request/UnlockRequest.java
  src/main/java/shop/wannab/userservice/auth/service/AuthService.java
  src/main/java/shop/wannab/userservice/user/controller/UserController.java
  src/main/java/shop/wannab/userservice/user/service/UserService.java
  src/main/java/shop/wannab/userservice/user/service/UserServiceImpl.java
Labels: Feature

#79 <78/save-exception>
  src/main/java/shop/wannab/userservice/auth/controller/AuthController.java
  src/main/java/shop/wannab/userservice/global/advice/GlobalExceptionHandler.java
  src/main/java/shop/wannab/userservice/user/service/UserService.java
  src/main/java/shop/wannab/userservice/user/service/UserServiceImpl.java
  src/main/java/shop/wannab/userservice/utils/ResponseCode.java
Labels: Fix, Refactor

#90 <89/point-pagination>
  http/request.http
  src/main/java/shop/wannab/userservice/point/controller/PointController.java
  src/main/java/shop/wannab/userservice/point/domain/dto/PageResponse.java
  src/main/java/shop/wannab/userservice/point/domain/dto/PointHistoryResponse.java
  src/main/java/shop/wannab/userservice/point/repository/PointHistoryRepository.java
  src/main/java/shop/wannab/userservice/point/service/PointHistoryService.java
  src/main/java/shop/wannab/userservice/point/service/PointHistoryServiceImpl.java
Labels: Fix

#127 <126/users-pagination>
  src/main/java/shop/wannab/userservice/auth/dto/response/UserResponse.java
  src/main/java/shop/wannab/userservice/auth/service/AuthService.java
  src/main/java/shop/wannab/userservice/point/repository/PointHistoryRepository.java
  src/main/java/shop/wannab/userservice/user/controller/AdminController.java
  src/main/java/shop/wannab/userservice/user/controller/UserController.java
  src/main/java/shop/wannab/userservice/user/domain/dto/request/AdminUserUpdateRequest.java
  src/main/java/shop/wannab/userservice/user/domain/dto/response/AdminPageUserResponse.java
  src/main/java/shop/wannab/userservice/user/domain/entity/User.java
  src/main/java/shop/wannab/userservice/user/service/UserService.java
  src/main/java/shop/wannab/userservice/user/service/UserServiceImpl.java
  src/test/java/shop/wannab/userservice/controller/AuthControllerTest.java
  src/test/java/shop/wannab/userservice/service/AuthServiceTest.java
Labels: Feature

#141 logback 설정 및 의존성 추가
  pom.xml
  src/main/java/shop/wannab/userservice/auth/controller/AuthController.java
  src/main/java/shop/wannab/userservice/auth/service/AuthService.java
  src/main/java/shop/wannab/userservice/point/controller/PointController.java
  src/main/java/shop/wannab/userservice/point/service/PointHistoryServiceImpl.java
  src/main/java/shop/wannab/userservice/point/service/PointPolicyServiceImpl.java
  src/main/java/shop/wannab/userservice/user/controller/AdminController.java
  src/main/java/shop/wannab/userservice/user/controller/UserController.java
  src/main/java/shop/wannab/userservice/user/domain/entity/User.java
  src/main/java/shop/wannab/userservice/user/service/UserServiceImpl.java
  src/main/resources/logback-spring.xml
  src/test/java/shop/wannab/userservice/service/AuthServiceTest.java
Labels: Feature

#146 feat: 에러 발생 시 두레이 메신저 알림
  pom.xml
  src/main/java/shop/wannab/userservice/global/alert/SendMessageRequest.java
  src/main/java/shop/wannab/userservice/global/alert/WebhookAppender.java
  src/main/resources/logback-spring.xml
Labels: Feature
